### ISSUE TITLE
Submissions should be rate limited by IP

### ISSUE THREAD

**Issue by chillu** [mandrew/silverstripe-quickfeedback#2]
Otherwise we allow attackers to fill up the database to easily (with up to 4MB text comments per feedback). The easiest measure would be to only store the latest feedback for a certain IP on a certain URL, overwriting any earlier submissions. Alternatively, we could implement session-based controls, but they're less effective against DDoS. I wouldn't use any captchas because we want to make feedback as easy as possible.

**Comment by mandrew** [comment]
Thanks @chillu we are looking at implementing this in a subsequent sprint and one of the aims was to add spam protection but I agree that adding captcha wouldn't be the best so will keep in mind the above options.

**Comment by camfindlay** [comment]
See #4
